### ISSUE TITLE
tree-view-sample does not work

### ISSUE THREAD

**Issue by 38elements** [microsoft/vscode-extension-samples#531]
I tried to tree-view-sample at 136822998740e9f019d06f912b3b6f06fd49b484. The following error message is displayed. tree-view-sample does not work.

```
Activating extension 'vscode-samples.custom-view-samples' failed: Class extends value undefined is not a constructor or null.
```

When I try to tree-view-sample at fbde91c6e2c071091be6b281fd33d81e1c0fcb06, tree-view-sample works normally.

My VSCode version is `1.62.3`.

**Comment by lion9** [comment]
Same here

**Comment by XueweiZheng** [comment]
I ran into the same problem. VSC v1.62.3

**Comment by windyoung1990** [comment]
same problem

**Comment by Cugtyt** [comment]
same

**Comment by rgosens2** [comment]
Yep, broken. Is this because vscode is deprecated?

https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode

**Comment by KamasamaK** [comment]
cc @alexr00

**Comment by alexr00** [comment]
Fix has been pushed. Thanks for bearing with this and for reporting the problem!

**Comment by rgosens2** [comment]
Package explorer: node dependencies still does not show node dependencies.

Activating extension 'vscode-samples.custom-view-samples' failed: Cannot find module 'jsonc-parser'
Require stack:
- /Users/rg/Downloads/tree-view-sample/out/jsonOutline.js
- /Users/rg/Downloads/tree-view-sample/out/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js.

It was still working in VSCode 1.42.0 with an older version of the tree-view-sample. Tested and screenshot made. 

![Screenshot 2021-12-04 at 12 57 49](https://user-images.githubusercontent.com/39185953/144708590-d966ec79-07b5-4859-8a2a-86ef39d66d9f.png)

**Comment by 38elements** [comment]
Did you  execute `npm install ` at `tree-view-sample` directory?
https://github.com/microsoft/vscode-extension-samples/blob/fbde91c6e2c071091be6b281fd33d81e1c0fcb06/tree-view-sample/package.json#L242

**Comment by rgosens2** [comment]
Thanks, `npm install` fixes it.
